"""GitHub integration — PR creation, branch management, repo cloning."""

import asyncio
import logging
import os
from typing import List, Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.patch_artifact import PatchArtifact
from app.models.session import Session
from app.models.repository import Repository

logger = logging.getLogger(__name__)
router = APIRouter()


# --- Schemas ---

class PRCreateRequest(BaseModel):
    branch_name: Optional[str] = None


class PRCreateResponse(BaseModel):
    branch: str
    files_changed: int
    message: str
    pr_url: Optional[str] = None
    commit_sha: Optional[str] = None


class PRStatusResponse(BaseModel):
    pr_url: Optional[str] = None
    branch: str
    state: str
    commits: int
    changed_files: int
    title: str


class GitHubRepoInfo(BaseModel):
    full_name: str
    clone_url: str
    default_branch: str
    private: bool


class GitHubUserResponse(BaseModel):
    login: str
    name: Optional[str] = None
    avatar_url: Optional[str] = None


class CloneRepoRequest(BaseModel):
    repo_url: str
    target_dir: Optional[str] = None


# --- Export PR ---

@router.post("/{session_id}/export-pr", response_model=PRCreateResponse, status_code=201)
async def export_patch_as_pr(
    session_id: int,
    body: PRCreateRequest = PRCreateRequest(),
    db: AsyncSession = Depends(get_db),
):
    session = await db.get(Session, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    repo = await db.get(Repository, session.repository_id)
    if not repo:
        raise HTTPException(status_code=404, detail="Repository not found")

    result = await db.execute(
        select(PatchArtifact)
        .where(PatchArtifact.session_id == session_id)
        .where(PatchArtifact.status == "accepted")
        .order_by(PatchArtifact.created_at.desc())
        .limit(1)
    )
    patch = result.scalar_one_or_none()
    if not patch:
        raise HTTPException(status_code=400, detail="No accepted patch found. Accept a patch first.")

    branch_name = body.branch_name or f"grokforge/session-{session_id}"
    changes = patch.changes or []

    # Init git if needed
    if not os.path.isdir(os.path.join(repo.path, ".git")):
        await _run_git(repo.path, "init")
        await _run_git(repo.path, "add", ".")
        await _run_git(repo.path, "commit", "-m", "initial commit")

    # Get current branch to return to
    try:
        original_branch = await _run_git(repo.path, "rev-parse", "--abbrev-ref", "HEAD")
    except Exception:
        original_branch = "main"

    try:
        # Check if branch already exists
        try:
            await _run_git(repo.path, "rev-parse", "--verify", branch_name)
            # Branch exists — delete it first
            await _run_git(repo.path, "branch", "-D", branch_name)
        except Exception:
            pass

        await _run_git(repo.path, "checkout", "-b", branch_name)

        # Apply changes
        files_changed = 0
        for change in changes:
            fp = change.get("file_path", "")
            patched = change.get("patched_content", "")
            if fp and patched:
                full_path = os.path.join(repo.path, fp)
                os.makedirs(os.path.dirname(full_path), exist_ok=True)
                with open(full_path, "w") as f:
                    f.write(patched)
                await _run_git(repo.path, "add", fp)
                files_changed += 1

        if files_changed == 0:
            await _run_git(repo.path, "checkout", original_branch)
            return PRCreateResponse(
                branch=branch_name, files_changed=0, message="No files to change"
            )

        commit_msg = f"feat: {session.title}\n\nGenerated by GrokForge session #{session_id}\n\n{patch.overall_rationale}"
        await _run_git(repo.path, "commit", "-m", commit_msg)
        commit_sha = await _run_git(repo.path, "rev-parse", "HEAD")

        # Push + create PR
        pr_url = None
        try:
            await _run_git(repo.path, "push", "-u", "origin", branch_name, "--force")
            logger.info("Pushed branch %s", branch_name)

            pr_body = (
                f"## Summary\n\n"
                f"{patch.overall_rationale}\n\n"
                f"---\n\n"
                f"*Generated by [GrokForge](https://github.com/omairqazi29/grokforge) "
                f"session #{session_id}*"
            )
            pr_output = await _run_cmd(
                repo.path, "gh", "pr", "create",
                "--title", session.title,
                "--body", pr_body,
                "--head", branch_name,
            )
            for line in pr_output.splitlines():
                line = line.strip()
                if line.startswith("https://github.com"):
                    pr_url = line
                    break
            logger.info("Created PR: %s", pr_url)
        except RuntimeError as e:
            error_msg = str(e)
            if "already exists" in error_msg.lower():
                # PR already exists — get the URL
                try:
                    pr_list = await _run_cmd(
                        repo.path, "gh", "pr", "list",
                        "--head", branch_name, "--json", "url", "--jq", ".[0].url"
                    )
                    if pr_list.strip():
                        pr_url = pr_list.strip()
                except Exception:
                    pass
            else:
                logger.warning("Could not create PR: %s", error_msg)

        await _run_git(repo.path, "checkout", original_branch)

        return PRCreateResponse(
            branch=branch_name,
            files_changed=files_changed,
            message=f"Branch {branch_name} pushed with {files_changed} file(s)" + (
                f" — PR created" if pr_url else " — push only (no remote or gh CLI)"
            ),
            pr_url=pr_url,
            commit_sha=commit_sha[:8] if commit_sha else None,
        )
    except Exception as e:
        try:
            await _run_git(repo.path, "checkout", original_branch)
        except Exception:
            pass
        raise HTTPException(status_code=500, detail=str(e))


# --- GitHub user info (checks if gh is authenticated) ---

@router.get("/github/user", response_model=GitHubUserResponse)
async def get_github_user():
    try:
        login = await _run_cmd(".", "gh", "api", "user", "--jq", ".login")
        name = await _run_cmd(".", "gh", "api", "user", "--jq", ".name")
        avatar = await _run_cmd(".", "gh", "api", "user", "--jq", ".avatar_url")
        return GitHubUserResponse(login=login.strip(), name=name.strip(), avatar_url=avatar.strip())
    except Exception:
        raise HTTPException(status_code=401, detail="Not authenticated with GitHub. Run 'gh auth login'.")


# --- List user's GitHub repos ---

@router.get("/github/repos", response_model=List[GitHubRepoInfo])
async def list_github_repos(limit: int = 30):
    try:
        output = await _run_cmd(
            ".", "gh", "repo", "list", "--json",
            "nameWithOwner,sshUrl,defaultBranchRef,isPrivate",
            "--limit", str(limit),
        )
        import json
        repos = json.loads(output)
        return [
            GitHubRepoInfo(
                full_name=r["nameWithOwner"],
                clone_url=r.get("sshUrl", ""),
                default_branch=r.get("defaultBranchRef", {}).get("name", "main") if r.get("defaultBranchRef") else "main",
                private=r.get("isPrivate", False),
            )
            for r in repos
        ]
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# --- Clone a GitHub repo ---

@router.post("/github/clone", response_model=dict)
async def clone_github_repo(body: CloneRepoRequest):
    target = body.target_dir or os.path.join(os.path.expanduser("~"), "Projects", body.repo_url.split("/")[-1])
    if os.path.exists(target):
        return {"path": target, "message": "Directory already exists"}
    try:
        await _run_cmd(".", "gh", "repo", "clone", body.repo_url, target)
        return {"path": target, "message": f"Cloned to {target}"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


# --- Helpers ---

async def _run_git(cwd: str, *args: str) -> str:
    return await _run_cmd(cwd, "git", *args)


async def _run_cmd(cwd: str, *args: str) -> str:
    proc = await asyncio.create_subprocess_exec(
        *args, cwd=cwd,
        stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=60)
    if proc.returncode != 0:
        raise RuntimeError(stderr.decode(errors="replace").strip())
    return stdout.decode(errors="replace").strip()
