"""P2: GitHub PR Generation — export accepted patches as git branches/PRs."""

import asyncio
import os
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.models.patch_artifact import PatchArtifact
from app.models.session import Session
from app.models.repository import Repository

router = APIRouter()


class PRCreateRequest(BaseModel):
    branch_name: Optional[str] = None


class PRCreateResponse(BaseModel):
    branch: str
    files_changed: int
    message: str
    pr_url: Optional[str] = None


@router.post(
    "/{session_id}/export-pr",
    response_model=PRCreateResponse,
    status_code=201,
)
async def export_patch_as_pr(
    session_id: int,
    body: PRCreateRequest = PRCreateRequest(),
    db: AsyncSession = Depends(get_db),
):
    session = await db.get(Session, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")

    repo = await db.get(Repository, session.repository_id)
    if not repo:
        raise HTTPException(status_code=404, detail="Repository not found")

    # Get the latest accepted patch
    from sqlalchemy import select

    result = await db.execute(
        select(PatchArtifact)
        .where(PatchArtifact.session_id == session_id)
        .where(PatchArtifact.status == "accepted")
        .order_by(PatchArtifact.created_at.desc())
        .limit(1)
    )
    patch = result.scalar_one_or_none()
    if not patch:
        raise HTTPException(status_code=400, detail="No accepted patch found. Accept a patch first.")

    branch_name = body.branch_name or f"grokforge/session-{session_id}"
    changes = patch.changes or []

    try:
        # Create branch
        await _run_git(repo.path, "checkout", "-b", branch_name)

        # Apply changes
        files_changed = 0
        for change in changes:
            file_path = os.path.join(repo.path, change.get("file_path", ""))
            patched = change.get("patched_content", "")
            if patched and file_path:
                os.makedirs(os.path.dirname(file_path), exist_ok=True)
                with open(file_path, "w") as f:
                    f.write(patched)
                await _run_git(repo.path, "add", change["file_path"])
                files_changed += 1

        if files_changed == 0:
            await _run_git(repo.path, "checkout", "-")
            return PRCreateResponse(
                branch=branch_name,
                files_changed=0,
                message="No files to change",
            )

        # Commit
        commit_msg = f"feat: {session.title}\n\nGenerated by GrokForge session #{session_id}"
        await _run_git(repo.path, "commit", "-m", commit_msg)

        # Try to push and create PR
        pr_url = None
        try:
            await _run_git(repo.path, "push", "-u", "origin", branch_name)
            pr_result = await _run_cmd(
                repo.path,
                "gh",
                "pr",
                "create",
                "--title",
                session.title,
                "--body",
                f"Generated by GrokForge\n\nSession #{session_id}\n\n{patch.overall_rationale}",
                "--head",
                branch_name,
            )
            # Extract PR URL from output
            for line in pr_result.splitlines():
                if "github.com" in line:
                    pr_url = line.strip()
                    break
        except Exception:
            pass  # Push/PR creation is best-effort

        # Switch back to original branch
        await _run_git(repo.path, "checkout", "-")

        return PRCreateResponse(
            branch=branch_name,
            files_changed=files_changed,
            message=f"Created branch {branch_name} with {files_changed} file(s)",
            pr_url=pr_url,
        )
    except Exception as e:
        # Try to clean up
        try:
            await _run_git(repo.path, "checkout", "-")
        except Exception:
            pass
        raise HTTPException(status_code=500, detail=str(e))


async def _run_git(cwd: str, *args: str) -> str:
    return await _run_cmd(cwd, "git", *args)


async def _run_cmd(cwd: str, *args: str) -> str:
    proc = await asyncio.create_subprocess_exec(
        *args,
        cwd=cwd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await asyncio.wait_for(proc.communicate(), timeout=30)
    if proc.returncode != 0:
        raise RuntimeError(stderr.decode(errors="replace").strip())
    return stdout.decode(errors="replace").strip()
